# Generated by Django 5.2.8 on 2025-11-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(help_text='Enter the customer name', max_length=20)),
                ('cust_id', models.IntegerField(help_text='Enter the customer id')),
                ('cust_dob', models.DateField(verbose_name='Enter the customer dob')),
            ],
        ),
    ]
